using System.Collections;
using System.Collections.Generic;
using UnityEngine;
 using TMPro; // INCLUDO ANCHE QUESTA USING PER POTER USARE GLI OGGETTI IN QUESTIONE

public class TextManager : MonoBehaviour
{
    // Variabili per lo script
    TextMeshProUGUI Testo_punteggio;

     TextMeshProUGUI Testo_Timer;

    public PlayerAttack player;

    public static int CurrentAmmo;
    public static int TotalAmmo;

    // Use this for initialization


    void Start ()
    {
         // Accedo al componente testo del oggetto e uso il metodo SetText per impostare il testo
         Testo_punteggio = gameObject.GetComponent<TextMeshProUGUI>();
         Testo_punteggio.SetText(" /");
         
    }
    // Update is called once per frame
    void Update ()
    {
         // Per impostare il testo posso anche usare la propriet√† text come per il testo di default
         CurrentAmmo = player.GetCurrentAmmo();
         TotalAmmo = player.GetTotalAmmo();

         if(TotalAmmo==-1)
         {
          Testo_punteggio.text = (" ");
         }

         else Testo_punteggio.text = CurrentAmmo.ToString()+ "/"+ TotalAmmo.ToString();

         
     
         

         
    }
}

